week4/modelproject/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('<int:id>', detail, name='detail'),
    path('new', new, name='new'),
    path('create', create, name='create'),
    path('update/<int:id>', update, name='update'),
    path('delete/<int:id>', delete, name='delete'),
]

week4/modelproject/modelproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import *
# from blog import views  # 이렇게 작성 하면 path('', views.home, name='home')으로 작성해주시면 됩니다. 
# 자세한 내용은 모듈 import 관련 내용을 검색해보시면 됩니다.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include('blog.urls')),
]

week4/modelproject/blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    writer = models.CharField(max_length=10)
    pub_date = models.DateTimeField()
    body = models.TextField()

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

week4/modelproject/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import *

# Create your views here.
def home(request):
    blogs = Blog.objects.all()
    return render(request, 'home.html', {'blogs':blogs})

def detail(request, id):
    # blog = Blog.objects.get(id = id)
    blog = get_object_or_404(Blog, pk = id)
    return render(request, 'detail.html', {'blog':blog})

def new(request):
	return render(request, 'new.html')

def create(request):
    new_blog = Blog()
    new_blog.title = request.POST['title']
    new_blog.writer = request.POST['writer']
    new_blog.body = request.POST['body']
    new_blog.pub_date = timezone.now()
    new_blog.save()
    return redirect('blog:detail', new_blog.id)

def update(request, id):
    blog = Blog.objects.get(id = id)
    if request.method == "POST":
        blog.title = request.POST["title"]
        blog.body = request.POST["body"]
        blog.save()
        return redirect('blog:detail', blog.id)
    return render(request, 'update.html', {'blog':blog})

def delete(request, id):
	blog = Blog.objects.get(id=id)
	blog.delete()
	return redirect("home")

week4/modelproject/blog/templates/detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{blog.title}}</h1>
    <div>
      작성자: {{blog.writer}}
      <br />
      날짜: {{blog.pub_date}}
    </div>
    <hr />
    <p>{{blog.body}}</p>
    <a href="{% url 'blog:update' blog.id %}">수정하기</a>
    <a href="{% url 'home' %}">돌아가기</a>
    <a href="{% url 'blog:delete' blog.id%}">Delete Post</a>
{% endblock %}

week4/modelproject/blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Blog Project</h1>
    <h4><a href="{% url 'blog:new' %}">New Post</a></h4>
    {% for blog in blogs %}
        {{blog.title}} </br>
        {{blog.writer}} </br>
        {{blog.summary}} 
        <a href="{% url 'blog:detail' blog.id %}">...more</a></br>
    {% endfor %}
{% endblock %}

week4/modelproject/blog/templates/new.html
{% extends 'base.html' %}
{% block content %}
    <h1>New Blog Entry</h1>
    <form action="{% url 'blog:create' %}" method="post">
        {%csrf_token%}
        <p>제목: <input type="text" name="title"></p>
        <p>작성자: <input type="text" name="writer"></p>
        본문: <br><textarea name="body" id="" cols="30" rows="10"></textarea><br>
        <button type='submit'>작성하기</button>
    </form>
{% endblock %}

week4/modelproject/blog/templates/update.html
{% extends 'base.html' %}
{% block content %}
    <form action="{% url 'blog:update' blog.id %}" method = "POST">
		{% csrf_token %}
        <h4>제목: </h4>
        <input type="text" name="title" value={{blog.title}}>
        <br>
        <br>
        <h4>본문: </h4>
        <textarea name="body" cols="30" rows="10">{{blog.body}}</textarea><br><br>
        <input type="submit" value="완료">
    </form>
{% endblock %}

week4/modelproject/modelproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>BLOG</title>
    <style>
      body {
        text-align: center;
        }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}"><img src = "{% static 'cat.jpeg' %}" alt = "" style="max-height: 50px;max-width: 50px;border-radius: 100%;"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'blog:new' %}">작성하기</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class = "container">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>